name: Build Docker image

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
    - v-2024.02.19-dev-actions
    - "*"
  pull_request:
    branches:
    - main
    - v-2024.02.19-dev-actions
    - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  name: ${{ github.ref_name }}

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: echo BRANCH IS ${{ env.name }} RIGHT?
      - name: Build Docker
        run: docker build . --file Dockerfile --tag localbuild/ngen-raven:${{ env.name }}
